
services:  
    # nginx
    # web:
    #     image: nginx:stable-alpine
    #     container_name: nginx-container
    #     ports:
    #         - "8080:80"
    #     volumes:
    #         - ./:/var/www
    #         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #         - mysql
    #     networks:
    #         - app-network

    # mysql
    mysql:
        image: mysql:8.3.0                                                                                                                                                                                                                                                                                                                     
        container_name: mysql-shop-demo
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./docker/mysql/config:/etc/mysql/conf.d
            - ./docker/mysql/database:/var/lib/mysql
        restart: always
        environment:
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
            MYSQL_PASSWORD: $DB_PASSWORD 
       
